server:
  port: 9004
spring:
  application:
    name: supergo-page
  resources:
    static-locations: classpath:templates/,classpath:static/,classpath:goods/
  mvc:
    view:
      suffix: .html  #视图解析器后缀
#  redis:
#    host: 127.0.0.1
#    port: 6379
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${eureka.instance.ip-address}:${server.port}
#    lease-renewal-interval-in-seconds: 3
#    lease-expiration-duration-in-seconds: 10
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
jwt:   #jwt测试数据
  config:
    key: abc123      #密匙
    ttl: 3600        #过期时间

