spring:
  application:
    name: supergo-mapper
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/supergo?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver