server:
  port: 9999
  servlet:
    context-path: /api #服务端口
spring:
  application:
    name: supergo-zuul #指定服务名
zuul:
  routes:
#    manager-web:
#      path: /manager/** # 这里是映射路径
#      serviceId: supergo-manager #服务的名称
#    portal-web:
#      path: /portal/**
#      serviceId: supergo-portal-web
    sso-web:
      path: /sso/**
      serviceId: supergo-sso
    page-web:
      path: /page/**
      serviceId: supergo-page
  retryable: true
  sensitive-headers: #请求头跨系统发送token秘钥
  host:
    connect-timeout-millis: 50000
    socket-timeout-millis: 50000
    connection-request-timeout-millis: 50000
#ribbon的超时时间
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /api/actuator/health #网关设置了根路径，默认监控路径发生了变化
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"





